# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_beepic.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_BeePic(object):
    def setupUi(self, BeePic):
        BeePic.setObjectName(_fromUtf8("BeePic"))
        BeePic.resize(426, 705)
        self.labelFolder = QtGui.QLabel(BeePic)
        self.labelFolder.setGeometry(QtCore.QRect(10, 96, 77, 20))
        self.labelFolder.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelFolder.setObjectName(_fromUtf8("labelFolder"))
        self.inputFolder = QtGui.QLineEdit(BeePic)
        self.inputFolder.setGeometry(QtCore.QRect(90, 95, 235, 22))
        self.inputFolder.setObjectName(_fromUtf8("inputFolder"))
        self.BrowseInFolder = QtGui.QPushButton(BeePic)
        self.BrowseInFolder.setGeometry(QtCore.QRect(326, 95, 60, 22))
        self.BrowseInFolder.setObjectName(_fromUtf8("BrowseInFolder"))
        self.labelPoints = QtGui.QLabel(BeePic)
        self.labelPoints.setGeometry(QtCore.QRect(10, 11, 77, 20))
        self.labelPoints.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelPoints.setObjectName(_fromUtf8("labelPoints"))
        self.labelImages = QtGui.QLabel(BeePic)
        self.labelImages.setGeometry(QtCore.QRect(10, 122, 71, 20))
        self.labelImages.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelImages.setObjectName(_fromUtf8("labelImages"))
        self.comboBoxPoints = QtGui.QComboBox(BeePic)
        self.comboBoxPoints.setGeometry(QtCore.QRect(90, 10, 235, 22))
        self.comboBoxPoints.setObjectName(_fromUtf8("comboBoxPoints"))
        self.comboBoxFilters = QtGui.QComboBox(BeePic)
        self.comboBoxFilters.setGeometry(QtCore.QRect(155, 120, 231, 22))
        self.comboBoxFilters.setObjectName(_fromUtf8("comboBoxFilters"))
        self.labelFields = QtGui.QLabel(BeePic)
        self.labelFields.setGeometry(QtCore.QRect(10, 34, 77, 20))
        self.labelFields.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelFields.setObjectName(_fromUtf8("labelFields"))
        self.comboBoxFields = QtGui.QComboBox(BeePic)
        self.comboBoxFields.setGeometry(QtCore.QRect(90, 33, 235, 22))
        self.comboBoxFields.setObjectName(_fromUtf8("comboBoxFields"))
        self.labelDelay = QtGui.QLabel(BeePic)
        self.labelDelay.setGeometry(QtCore.QRect(10, 310, 171, 20))
        self.labelDelay.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelDelay.setObjectName(_fromUtf8("labelDelay"))
        self.spinBoxDelay = QtGui.QSpinBox(BeePic)
        self.spinBoxDelay.setGeometry(QtCore.QRect(180, 310, 111, 22))
        self.spinBoxDelay.setMinimum(-999999)
        self.spinBoxDelay.setMaximum(999999)
        self.spinBoxDelay.setObjectName(_fromUtf8("spinBoxDelay"))
        self.labelOutput = QtGui.QLabel(BeePic)
        self.labelOutput.setGeometry(QtCore.QRect(10, 550, 101, 20))
        self.labelOutput.setObjectName(_fromUtf8("labelOutput"))
        self.lineEditOutput = QtGui.QLineEdit(BeePic)
        self.lineEditOutput.setGeometry(QtCore.QRect(110, 550, 212, 22))
        self.lineEditOutput.setObjectName(_fromUtf8("lineEditOutput"))
        self.BrowseOutput = QtGui.QPushButton(BeePic)
        self.BrowseOutput.setGeometry(QtCore.QRect(330, 550, 60, 22))
        self.BrowseOutput.setObjectName(_fromUtf8("BrowseOutput"))
        self.textBrowser = QtGui.QTextBrowser(BeePic)
        self.textBrowser.setGeometry(QtCore.QRect(10, 370, 376, 151))
        self.textBrowser.setObjectName(_fromUtf8("textBrowser"))
        self.listWidget = QtGui.QListWidget(BeePic)
        self.listWidget.setGeometry(QtCore.QRect(10, 143, 376, 130))
        self.listWidget.setObjectName(_fromUtf8("listWidget"))
        self.labelTimeField = QtGui.QLabel(BeePic)
        self.labelTimeField.setGeometry(QtCore.QRect(10, 57, 77, 20))
        self.labelTimeField.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelTimeField.setObjectName(_fromUtf8("labelTimeField"))
        self.editFieldTimeFormat = QtGui.QLineEdit(BeePic)
        self.editFieldTimeFormat.setGeometry(QtCore.QRect(90, 56, 235, 22))
        self.editFieldTimeFormat.setObjectName(_fromUtf8("editFieldTimeFormat"))
        self.ButtonHelp1 = QtGui.QPushButton(BeePic)
        self.ButtonHelp1.setGeometry(QtCore.QRect(326, 56, 22, 22))
        self.ButtonHelp1.setObjectName(_fromUtf8("ButtonHelp1"))
        self.labelTimeField_2 = QtGui.QLabel(BeePic)
        self.labelTimeField_2.setGeometry(QtCore.QRect(10, 277, 98, 20))
        self.labelTimeField_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelTimeField_2.setObjectName(_fromUtf8("labelTimeField_2"))
        self.editImageTimeFormat = QtGui.QLineEdit(BeePic)
        self.editImageTimeFormat.setGeometry(QtCore.QRect(112, 276, 252, 22))
        self.editImageTimeFormat.setObjectName(_fromUtf8("editImageTimeFormat"))
        self.ButtonHelp2 = QtGui.QPushButton(BeePic)
        self.ButtonHelp2.setGeometry(QtCore.QRect(366, 276, 22, 22))
        self.ButtonHelp2.setObjectName(_fromUtf8("ButtonHelp2"))
        self.checkShowPosition = QtGui.QCheckBox(BeePic)
        self.checkShowPosition.setGeometry(QtCore.QRect(10, 520, 201, 21))
        self.checkShowPosition.setObjectName(_fromUtf8("checkShowPosition"))
        self.progressBar = QtGui.QProgressBar(BeePic)
        self.progressBar.setGeometry(QtCore.QRect(20, 610, 376, 23))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName(_fromUtf8("progressBar"))
        self.ButtonRefresh = QtGui.QPushButton(BeePic)
        self.ButtonRefresh.setGeometry(QtCore.QRect(326, 10, 60, 22))
        self.ButtonRefresh.setObjectName(_fromUtf8("ButtonRefresh"))
        self.cancelButton = QtGui.QPushButton(BeePic)
        self.cancelButton.setGeometry(QtCore.QRect(280, 650, 100, 32))
        self.cancelButton.setObjectName(_fromUtf8("cancelButton"))
        self.okButton = QtGui.QPushButton(BeePic)
        self.okButton.setGeometry(QtCore.QRect(170, 650, 100, 32))
        self.okButton.setObjectName(_fromUtf8("okButton"))
        self.helpButton = QtGui.QPushButton(BeePic)
        self.helpButton.setGeometry(QtCore.QRect(10, 650, 100, 32))
        self.helpButton.setObjectName(_fromUtf8("helpButton"))
        self.checkKml = QtGui.QCheckBox(BeePic)
        self.checkKml.setGeometry(QtCore.QRect(110, 580, 201, 21))
        self.checkKml.setObjectName(_fromUtf8("checkKml"))
        self.radioButton = QtGui.QRadioButton(BeePic)
        self.radioButton.setGeometry(QtCore.QRect(290, 340, 101, 17))
        self.radioButton.setObjectName(_fromUtf8("radioButton"))
        self.radioButton_2 = QtGui.QRadioButton(BeePic)
        self.radioButton_2.setGeometry(QtCore.QRect(150, 340, 131, 17))
        self.radioButton_2.setChecked(True)
        self.radioButton_2.setObjectName(_fromUtf8("radioButton_2"))
        self.labelDelay_2 = QtGui.QLabel(BeePic)
        self.labelDelay_2.setGeometry(QtCore.QRect(10, 336, 151, 20))
        self.labelDelay_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelDelay_2.setObjectName(_fromUtf8("labelDelay_2"))

        self.retranslateUi(BeePic)
        QtCore.QMetaObject.connectSlotsByName(BeePic)

    def retranslateUi(self, BeePic):
        BeePic.setWindowTitle(_translate("BeePic", "BeePic", None))
        self.labelFolder.setText(_translate("BeePic", "Image folder:", None))
        self.BrowseInFolder.setText(_translate("BeePic", "Browse", None))
        self.labelPoints.setText(_translate("BeePic", "Time points:", None))
        self.labelImages.setText(_translate("BeePic", "Images:", None))
        self.labelFields.setText(_translate("BeePic", "Time field:", None))
        self.labelDelay.setText(_translate("BeePic", "Image time delay (seconds):", None))
        self.labelOutput.setText(_translate("BeePic", "Output shapefile:", None))
        self.BrowseOutput.setText(_translate("BeePic", "Browse", None))
        self.labelTimeField.setText(_translate("BeePic", "Time format:", None))
        self.editFieldTimeFormat.setText(_translate("BeePic", "%Y-%m-%d %H:%M:%S", None))
        self.ButtonHelp1.setText(_translate("BeePic", "?", None))
        self.labelTimeField_2.setText(_translate("BeePic", "Exif time format:", None))
        self.editImageTimeFormat.setText(_translate("BeePic", "%Y:%m:%d %H:%M:%S", None))
        self.ButtonHelp2.setText(_translate("BeePic", "?", None))
        self.checkShowPosition.setText(_translate("BeePic", "Show the position on the map", None))
        self.ButtonRefresh.setText(_translate("BeePic", "Refresh", None))
        self.cancelButton.setText(_translate("BeePic", "Cancel", None))
        self.okButton.setText(_translate("BeePic", "Ok", None))
        self.helpButton.setText(_translate("BeePic", "Help", None))
        self.checkKml.setText(_translate("BeePic", "Create .kml", None))
        self.radioButton.setText(_translate("BeePic", "GPS Coordinates", None))
        self.radioButton_2.setText(_translate("BeePic", "Calculated Coordinates", None))
        self.labelDelay_2.setText(_translate("BeePic", "Choose coordinate to use :", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    BeePic = QtGui.QDialog()
    ui = Ui_BeePic()
    ui.setupUi(BeePic)
    BeePic.show()
    sys.exit(app.exec_())

